### ISSUE TITLE
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by 1353604736** [pangao1990/myChat#1]
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by pangao1990** [comment]
@1353604736 你好。这是由urllib3模块引起的错误。目前可以采取降级urllib3模块，或者将HTTPS代理到HTTP的方法解决。
我已经修复了该问题，请下载新版使用。
https://github.com/pangao1990/myChat/releases/latest

**Comment by 1353604736** [comment]
![屏幕截图 2023-04-04 114341](https://user-images.githubusercontent.com/12869582/229681867-94372e16-425a-4943-8fd0-5980da2aaa2a.jpg)

**Comment by 1353604736** [comment]
好了，可用，支持
