### ISSUE TITLE
我想自己编译学习看看，运行main.py后出现这个，需要如何做呢？

### ISSUE THREAD

**Issue by 52yaoer** [pangao1990/myChat#3]
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/13000992/233756485-926e0837-558d-4e6c-94a4-7b46c2ff6216.png">
自己编译，打包，命令流程怎么做的？能指导下么？

**Comment by pangao1990** [comment]
myChat软件是基于 https://github.com/pangao1990/vue-pywebview-pyinstaller 来开发的，编译打包流程，可以参考vue-pywebview-pyinstaller 中给出的教程。
