### ISSUE TITLE
macos的intel的环境下，沟通的内容不能复制。

### ISSUE THREAD

**Issue by miladuojx** [pangao1990/myChat#5]
问题环境：macbook pro intel环境下
M1环境下，复制没有问题

**Comment by pangao1990** [comment]
@miladuojx 你好，可以双击或者点击滑动选择文字，然后command+c复制。请问这样的操作可以复制吗？

**Comment by pangao1990** [comment]
![copy](https://user-images.githubusercontent.com/36030293/234437383-4f20cd65-d4e6-48ab-ba16-88c7688bc0f7.gif)

**Comment by miladuojx** [comment]
> @pangao1990 

我不是不会复制，是肯定intel cpu环境下，不能复制，我有两个macbook pro的本子，M1芯片下就可以正常复制。
另外，我同事也是intel的macbook pro也是不能复制，目前升级到了v2.3.0的版本，还是不能复制。
指针没法选择，点上面的字无任何反应。

**Comment by pangao1990** [comment]
抱歉，我用了朋友的mac Intel版本，的确无法复制。M芯片和win都可以正常复制。我今天找个mac Intel版本测试这个问题，感谢你的反馈。 @miladuojx

**Comment by pangao1990** [comment]
@miladuojx 你好，V2.3.1版本已经修复了macOS的Intel芯片平台无法复制消息的问题，欢迎试用。
