### ISSUE TITLE
【bug】主题广场 一个都用不了，每次倒计时300秒

### ISSUE THREAD

**Issue by Thomas-cat** [pangao1990/myChat#7]
随便聊聊都没问题。
就是主题广场任何一个都会倒计时，一直卡着
怎么回事，，，

**Comment by pangao1990** [comment]
你好，我刚才测试了下，主题广场的场景是可以正常聊天的。我猜测，是不是你那边在用主题广场的场景时候正巧网络不佳。因为主题广场的场景没有做什么特殊的处理，仅仅是预设了一些信息，和【随便聊聊】的场景是一样的。理论上来说，要么都不能聊，要么都能聊。。。

![截图](https://user-images.githubusercontent.com/36030293/236369779-59cf9095-a09f-46ec-b9cd-aee1c45e18b9.png)
