### ISSUE TITLE
能检测更新，不能下载

### ISSUE THREAD

**Issue by 1353604736** [pangao1990/myChat#9]
能检测更新，不能下载
![MouseInc 113536](https://github.com/pangao1990/myChat/assets/12869582/8882d444-ef9e-4a3b-99f2-2bcda8a4499d)

**Comment by pangao1990** [comment]
@1353604736 你好，myChat的软件更新是基于Github Releases开发。在Github官网访问困难的时候可能会出现无法自动下载更新，请尝试点击【手动更新】。会直接跳转到 https://github.com/pangao1990/myChat/releases 下载页面。

<img width="499" alt="image" src="https://github.com/pangao1990/myChat/assets/36030293/f44ecc68-6d59-4e58-94f6-6b66ecf169bf">
